version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "NO TESTS"
      - deploy:
          name: "Deploy to server when on master"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh-keyscan neamar.fr >> ~/.ssh/known_hosts
              git push dokku@neamar.fr:neamar master -f
            fi
