<?php
defined('CALL_FROM_CRON') or exit('Forbidden');


@mysql_query('ANALYZE TABLE `CCDS_Joueurs` ,
`CCDS_Moyennes_Niveaux` ,
`CCDS_Niveau_Code` ,
`CCDS_Niveau_Data` ,
`CCDS_Niveau_Perso` ,
`CCDS_URL` ,
`ECHO_AppartientGroupe` ,
`ECHO_Articles` ,
`ECHO_AutorisationGroupe` ,
`ECHO_AutorisationUtilisateur` ,
`ECHO_Categories` ,
`ECHO_Groupes` ,
`ECHO_Utilisateurs` ,
`Finder` ,
`Finder_Controles` ,
`Finder_Events` ,
`Finder_Papiers` ,
`Finder_Telephone2` ,
`Followings` ,
`Lachal_Citations` ,
`Lachal_Defis` ,
`Lachal_Expression` ,
`Lachal_Histoires` ,
`Lachal_Relations` ,
`MISC_LDJ` ,
`MISC_Mots` ,
`OMNI_Anecdotes` ,
`OMNI_Auteurs` ,
`OMNI_Categories` ,
`OMNI_Forum` ,
`OMNI_Liens` ,
`OMNI_Mails` ,
`OMNI_Modifs` ,
`OMNI_More` ,
`OMNI_Omnilogismes` ,
`OMNI_Propositions` ,
`OMNI_Redirection` ,
`OT2J_Textes` ,
`PALA_Articles` ,
`PALA_Commentaires` ,
`pma_bookmark` ,
`pma_column_info` ,
`pma_designer_coords` ,
`pma_history` ,
`pma_pdf_pages` ,
`pma_relation` ,
`pma_table_coords` ,
`pma_table_info` ,
`TEX_Block` ,
`TEX_Environnements` ,
`TEX_Inline` ,
`TEX_Types` ,
`TYPO_Textes` ,
`_Menus` ,
`_TimeLine` ');

@mysql_query('OPTIMIZE TABLE `CCDS_Joueurs` , `CCDS_Moyennes_Niveaux` , `CCDS_Niveau_Code` , `CCDS_Niveau_Data` , `CCDS_Niveau_Perso` , `CCDS_URL` , `ECHO_AppartientGroupe`  , `ECHO_Articles` , `ECHO_AutorisationGroupe`  , `ECHO_AutorisationUtilisateur`  , `ECHO_Categories` , `ECHO_Groupes` , `ECHO_Utilisateurs` , `Finder` , `Finder_Controles` , `Finder_Events` , `Finder_Papiers` , `Finder_Telephone2` , `Followings` , `Lachal_Citations` , `Lachal_Defis` , `Lachal_Expression` , `Lachal_Histoires` , `Lachal_Relations` , `MISC_LDJ` , `MISC_Mots` , `OMNI_Anecdotes` , `OMNI_Auteurs` , `OMNI_Categories` , `OMNI_Forum` , `OMNI_Liens` , `OMNI_Mails` , `OMNI_Modifs` , `OMNI_More` , `OMNI_Omnilogismes` , `OMNI_Propositions` , `OMNI_Redirection` , `OT2J_Textes` , `PALA_Articles` , `PALA_Commentaires` , `pma_bookmark` , `pma_column_info` , `pma_designer_coords` , `pma_history` , `pma_pdf_pages` , `pma_relation` , `pma_table_coords` , `pma_table_info` , `TEX_Block` , `TEX_Environnements` , `TEX_Inline` , `TEX_Types` , `TYPO_Textes` , `_Menus` , `_TimeLine` ');